# TITANIC DATASET

# Look at Data

In [166]:
https://www.dataquest.io/blog/pandas-cheat-sheet/

SyntaxError: invalid syntax (<ipython-input-166-e7b89cbc4037>, line 1)

In [167]:
https://pandas.pydata.org/docs/getting_started/intro_tutorials/02_read_write.html

SyntaxError: invalid syntax (<ipython-input-167-ba7437789f28>, line 1)

In [ ]:
https://www.codegrepper.com/code-examples/delphi/how+to+drop+only+nan+values+in+pandas

In [ ]:
https://chrisalbon.com/python/data_wrangling/pandas_dropping_column_and_rows/

In [168]:
visulization

NameError: name 'visulization' is not defined

In [2]:
# Reading data in Pandas

import pandas as pd # import Pandas

df = pd.read_csv("titanic_data.csv") # Read data file
df.head()
df[0:5] # Display data

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [4]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [5]:
df.tail()

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [6]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [10]:
df[["Age","Sex"]]

KeyError: ('Age', 'Sex')

In [13]:
df[df['Age']>35]

PassengerId  Survived  Pclass  \
1              2         1       1   
6              7         0       1   
11            12         1       1   
13            14         0       3   
15            16         1       2   
..           ...       ...     ...   
865          866         1       2   
871          872         1       1   
873          874         0       3   
879          880         1       1   
885          886         0       3   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
13                         Andersson, Mr. Anders Johan    male  39.0      1   
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
..                                                 ...     ...   ...    ...   
865                           Bystrom, Mrs. (Karolina)  female  42.0      0   
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0      1   
873                        Vander Cruyssen, Mr. Victor    male  47.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   

     Parch    Ticket     Fare Cabin Embarked  
1        0  PC 17599  71.2833   C85        C  
6        0     17463  51.8625   E46        S  
11       0    113783  26.5500  C103        S  
13       5    347082  31.2750   NaN        S  
15       0    248706  16.0000   NaN        S  
..     ...       ...      ...   ...      ...  
865      0    236852  13.0000   NaN        S  
871      1     11751  52.5542   D35        S  
873      0    345765   9.0000   NaN        S  
879      1     11767  83.1583   C50        C  
885      5    382652  29.1250   NaN        Q  

[217 rows x 12 columns]

In [14]:
df[df['Age']>35].shape

(217, 12)

In [15]:
df[df['Age']>35].dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [16]:
df["Age"]

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [ ]:
**csv to excel**

In [ ]:
import pandas as pd

read_file = pd.read_csv (r"titanic_data.csv")
read_file.to_excel (r'titanic_data.xlsx', index = None, header=True)

In [ ]:
df.to_excel('titanic.xlsx', sheet_name='passengers', index=False)

In [ ]:
# Reading the csv file 
df_new = pd.read_csv('titanic_data.csv') 
  
# saving xlsx file 
GFG = pd.ExcelWriter('titanic_data.xlsx') 
df_new.to_excel(GFG, index = False) 

In [ ]:
pd.read_csv('titanic_data.csv')
   .to_excel('titanic_data.xlsx')

In [ ]:
**I’m interested in the Titanic passengers from cabin class 2 and 3.**

In [22]:
df[df['Pclass']==2, df['Pclass']==3]

TypeError: '(0      False
1      False
2      False
3      False
4      False
       ...  
886     True
887    False
888    False
889    False
890    False
Name: Pclass, Length: 891, dtype: bool, 0       True
1      False
2       True
3      False
4       True
       ...  
886    False
887    False
888     True
889    False
890     True
Name: Pclass, Length: 891, dtype: bool)' is an invalid key

In [ ]:
I want to work with passenger data for which the age is known.

In [24]:
 df[df['Age'].notna()]

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
885          886         0       3   
886          887         0       2   
887          888         1       1   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
885      5            382652  29.1250   NaN        Q  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[714 rows x 12 columns]

In [ ]:
I’m interested in the names of the passengers older than 35 years.

In [25]:
 df[df['Age']>35]

PassengerId  Survived  Pclass  \
1              2         1       1   
6              7         0       1   
11            12         1       1   
13            14         0       3   
15            16         1       2   
..           ...       ...     ...   
865          866         1       2   
871          872         1       1   
873          874         0       3   
879          880         1       1   
885          886         0       3   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
13                         Andersson, Mr. Anders Johan    male  39.0      1   
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
..                                                 ...     ...   ...    ...   
865                           Bystrom, Mrs. (Karolina)  female  42.0      0   
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0      1   
873                        Vander Cruyssen, Mr. Victor    male  47.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   

     Parch    Ticket     Fare Cabin Embarked  
1        0  PC 17599  71.2833   C85        C  
6        0     17463  51.8625   E46        S  
11       0    113783  26.5500  C103        S  
13       5    347082  31.2750   NaN        S  
15       0    248706  16.0000   NaN        S  
..     ...       ...      ...   ...      ...  
865      0    236852  13.0000   NaN        S  
871      1     11751  52.5542   D35        S  
873      0    345765   9.0000   NaN        S  
879      1     11767  83.1583   C50        C  
885      5    382652  29.1250   NaN        Q  

[217 rows x 12 columns]

In [30]:
 k=df[df['Age']>35]

PassengerId  Survived  Pclass  \
1              2         1       1   
6              7         0       1   
11            12         1       1   
13            14         0       3   
15            16         1       2   
..           ...       ...     ...   
865          866         1       2   
871          872         1       1   
873          874         0       3   
879          880         1       1   
885          886         0       3   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
13                         Andersson, Mr. Anders Johan    male  39.0      1   
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
..                                                 ...     ...   ...    ...   
865                           Bystrom, Mrs. (Karolina)  female  42.0      0   
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0      1   
873                        Vander Cruyssen, Mr. Victor    male  47.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   

     Parch    Ticket     Fare Cabin Embarked  
1        0  PC 17599  71.2833   C85        C  
6        0     17463  51.8625   E46        S  
11       0    113783  26.5500  C103        S  
13       5    347082  31.2750   NaN        S  
15       0    248706  16.0000   NaN        S  
..     ...       ...      ...   ...      ...  
865      0    236852  13.0000   NaN        S  
871      1     11751  52.5542   D35        S  
873      0    345765   9.0000   NaN        S  
879      1     11767  83.1583   C50        C  
885      5    382652  29.1250   NaN        Q  

[217 rows x 12 columns]

In [32]:
df[df['Age']>35]["Name"]

1      Cumings, Mrs. John Bradley (Florence Briggs Th...
6                                McCarthy, Mr. Timothy J
11                              Bonnell, Miss. Elizabeth
13                           Andersson, Mr. Anders Johan
15                      Hewlett, Mrs. (Mary D Kingcome) 
                             ...                        
865                             Bystrom, Mrs. (Karolina)
871     Beckwith, Mrs. Richard Leonard (Sallie Monypeny)
873                          Vander Cruyssen, Mr. Victor
879        Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)
885                 Rice, Mrs. William (Margaret Norton)
Name: Name, Length: 217, dtype: object

In [ ]:
 to assign the name anonymous to the first 3 elements of the third column:

In [40]:
df.lock[0:3,4]=="Anormous"

AttributeError: 'DataFrame' object has no attribute 'lock'

In [ ]:
What is the average age for male versus female Titanic passengers?

The **columns** function gives the name of the columns in your data file.

In [172]:
column=list(df.columns)
print(column)

['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']


In [173]:
What is the average age of the Titanic passengers?

Object `passengers` not found.


In [ ]:
What is the average age of the Titanic passengers

In [174]:
df['Age'].mean()

29.69911764705882

In [175]:
Approx. 30 years

SyntaxError: invalid syntax (<ipython-input-175-ed1fd4480ba3>, line 1)

In [176]:
What is the maximum and minimum age of the Titanic passengers?

Object `passengers` not found.


In [ ]:
What is the maximum and minimum age of the Titanic passengers

In [177]:
df['Age'].max()

80.0

In [178]:
df['Age'].min()

0.42

In [179]:
Did the minimum age person survive?

Object `survive` not found.


In [ ]:
Did the minimum age person survive

In [180]:
df[(df['Age'] ==0.42) & (df['Survived'] >0)]

PassengerId  Survived  Pclass                             Name   Sex  \
803          804         1       3  Thomas, Master. Assad Alexander  male   

      Age  SibSp  Parch Ticket    Fare Cabin Embarked  
803  0.42      0      1   2625  8.5167   NaN        C

In [181]:
yes thats great new

SyntaxError: invalid syntax (<ipython-input-181-67c41af89611>, line 1)

In [182]:
What is the median age and ticket fare price of the Titanic passengers?

Object `passengers` not found.


In [ ]:
What is the median age and ticket fare price of the Titanic passengers

In [183]:
(df['Age']).median()

28.0

In [184]:
(df['Fare']).median()

14.4542

In [185]:
df[["Fare", "Age"]].median()

Fare    14.4542
Age     28.0000
dtype: float64

In [186]:
What is the average age for male versus female Titanic passengers?

Object `passengers` not found.


In [ ]:
What is the average age for male versus female Titanic passengers

In [187]:
df.groupby('Sex')['Age'].mean()

Sex
female    27.915709
male      30.726645
Name: Age, dtype: float64

In [188]:
group by sex and age

SyntaxError: invalid syntax (<ipython-input-188-fe9410ee28fa>, line 1)

In [189]:
df[['Sex','Age']]

Sex   Age
0      male  22.0
1    female  38.0
2    female  26.0
3    female  35.0
4      male  35.0
..      ...   ...
886    male  27.0
887  female  19.0
888  female   NaN
889    male  26.0
890    male  32.0

[891 rows x 2 columns]

 Another way to find the # of passengers older than 35 years ?

In [190]:
df[df['Age']>35].count()

PassengerId    217
Survived       217
Pclass         217
Name           217
Sex            217
Age            217
SibSp          217
Parch          217
Ticket         217
Fare           217
Cabin           95
Embarked       215
dtype: int64

In [191]:
age_above_35=df[df['Age']>35]
age_above_35.head()

PassengerId  Survived  Pclass  \
1             2         1       1   
6             7         0       1   
11           12         1       1   
13           14         0       3   
15           16         1       2   

                                                 Name     Sex   Age  SibSp  \
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
6                             McCarthy, Mr. Timothy J    male  54.0      0   
11                           Bonnell, Miss. Elizabeth  female  58.0      0   
13                        Andersson, Mr. Anders Johan    male  39.0      1   
15                   Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   

    Parch    Ticket     Fare Cabin Embarked  
1       0  PC 17599  71.2833   C85        C  
6       0     17463  51.8625   E46        S  
11      0    113783  26.5500  C103        S  
13      5    347082  31.2750   NaN        S  
15      0    248706  16.0000   NaN        S

In [192]:
age_above_35.shape

(217, 12)

In [193]:
’m interested in the Titanic passengers from cabin class 2 and 3.

SyntaxError: invalid character in identifier (<ipython-input-193-02eacfbef16c>, line 1)

In [194]:
df[(df['Pclass'] ==2) & (df['Pclass'] ==3)]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [195]:
df['Pclass']

0      3
1      1
2      3
3      1
4      3
      ..
886    2
887    1
888    3
889    1
890    3
Name: Pclass, Length: 891, dtype: int64

In [196]:
df[df['Pclass'] ==1]

PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
6              7         0       1   
11            12         1       1   
23            24         1       1   
..           ...       ...     ...   
871          872         1       1   
872          873         0       1   
879          880         1       1   
887          888         1       1   
889          890         1       1   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
23                        Sloper, Mr. William Thompson    male  28.0      0   
..                                                 ...     ...   ...    ...   
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0      1   
872                           Carlsson, Mr. Frans Olof    male  33.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
889                              Behr, Mr. Karl Howell    male  26.0      0   

     Parch    Ticket     Fare        Cabin Embarked  
1        0  PC 17599  71.2833          C85        C  
3        0    113803  53.1000         C123        S  
6        0     17463  51.8625          E46        S  
11       0    113783  26.5500         C103        S  
23       0    113788  35.5000           A6        S  
..     ...       ...      ...          ...      ...  
871      1     11751  52.5542          D35        S  
872      0       695   5.0000  B51 B53 B55        S  
879      1     11767  83.1583          C50        C  
887      0    112053  30.0000          B42        S  
889      0    111369  30.0000         C148        C  

[216 rows x 12 columns]

In [197]:
891-216

675

675 is number of the Titanic passengers from cabin class 2 and 3.

In [199]:
df[(df['Pclass'] > 1)]

PassengerId  Survived  Pclass                                      Name  \
0              1         0       3                   Braund, Mr. Owen Harris   
2              3         1       3                    Heikkinen, Miss. Laina   
4              5         0       3                  Allen, Mr. William Henry   
5              6         0       3                          Moran, Mr. James   
7              8         0       3            Palsson, Master. Gosta Leonard   
..           ...       ...     ...                                       ...   
884          885         0       3                    Sutehall, Mr. Henry Jr   
885          886         0       3      Rice, Mrs. William (Margaret Norton)   
886          887         0       2                     Montvila, Rev. Juozas   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
0      male  22.0      1      0         A/5 21171   7.2500   NaN        S  
2    female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S  
4      male  35.0      0      0            373450   8.0500   NaN        S  
5      male   NaN      0      0            330877   8.4583   NaN        Q  
7      male   2.0      3      1            349909  21.0750   NaN        S  
..      ...   ...    ...    ...               ...      ...   ...      ...  
884    male  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S  
885  female  39.0      0      5            382652  29.1250   NaN        Q  
886    male  27.0      0      0            211536  13.0000   NaN        S  
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S  
890    male  32.0      0      0            370376   7.7500   NaN        Q  

[675 rows x 12 columns]

In [200]:
df[df["Pclass"].isin([2, 3])]

PassengerId  Survived  Pclass                                      Name  \
0              1         0       3                   Braund, Mr. Owen Harris   
2              3         1       3                    Heikkinen, Miss. Laina   
4              5         0       3                  Allen, Mr. William Henry   
5              6         0       3                          Moran, Mr. James   
7              8         0       3            Palsson, Master. Gosta Leonard   
..           ...       ...     ...                                       ...   
884          885         0       3                    Sutehall, Mr. Henry Jr   
885          886         0       3      Rice, Mrs. William (Margaret Norton)   
886          887         0       2                     Montvila, Rev. Juozas   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
0      male  22.0      1      0         A/5 21171   7.2500   NaN        S  
2    female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S  
4      male  35.0      0      0            373450   8.0500   NaN        S  
5      male   NaN      0      0            330877   8.4583   NaN        Q  
7      male   2.0      3      1            349909  21.0750   NaN        S  
..      ...   ...    ...    ...               ...      ...   ...      ...  
884    male  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S  
885  female  39.0      0      5            382652  29.1250   NaN        Q  
886    male  27.0      0      0            211536  13.0000   NaN        S  
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S  
890    male  32.0      0      0            370376   7.7500   NaN        Q  

[675 rows x 12 columns]

In [ ]:
I want to work with passenger data for which the age is known.

In [206]:
df.dropna(subset=['Age'])

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
885          886         0       3   
886          887         0       2   
887          888         1       1   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
885      5            382652  29.1250   NaN        Q  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[714 rows x 12 columns]

In [203]:
df = df[df['Age'].notna()]

In [205]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
885          886         0       3   
886          887         0       2   
887          888         1       1   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
885      5            382652  29.1250   NaN        Q  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[714 rows x 12 columns]

**I’m interested in the names of the passengers older than 35 years.**

In [209]:
df[df['Age']>35]

PassengerId  Survived  Pclass  \
1              2         1       1   
6              7         0       1   
11            12         1       1   
13            14         0       3   
15            16         1       2   
..           ...       ...     ...   
865          866         1       2   
871          872         1       1   
873          874         0       3   
879          880         1       1   
885          886         0       3   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
13                         Andersson, Mr. Anders Johan    male  39.0      1   
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
..                                                 ...     ...   ...    ...   
865                           Bystrom, Mrs. (Karolina)  female  42.0      0   
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0      1   
873                        Vander Cruyssen, Mr. Victor    male  47.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   

     Parch    Ticket     Fare Cabin Embarked  
1        0  PC 17599  71.2833   C85        C  
6        0     17463  51.8625   E46        S  
11       0    113783  26.5500  C103        S  
13       5    347082  31.2750   NaN        S  
15       0    248706  16.0000   NaN        S  
..     ...       ...      ...   ...      ...  
865      0    236852  13.0000   NaN        S  
871      1     11751  52.5542   D35        S  
873      0    345765   9.0000   NaN        S  
879      1     11767  83.1583   C50        C  
885      5    382652  29.1250   NaN        Q  

[217 rows x 12 columns]

In [ ]:
**I’m interested in rows 10 till 25 and columns 3 to 5**

In [235]:
df_drop_c=df.copy() # Copy to avoid modifying the original data
Select_column=column[0:2] # Select columns that have missing #columns described above # look at the non-null columns above
Select_column1= column[6:]
df_drop_c.drop(Select_column, axis=1, inplace=True)
df_drop_c2=df_drop_c.copy()
df_drop_c2.drop(Select_column1, axis=1, inplace=True)

df_drop_c2.drop(df.index[[-2]], inplace=True)
df_drop_c2
df_drop_c2[-2:]



Pclass                          Name     Sex   Age
887       1  Graham, Miss. Margaret Edith  female  19.0
890       3           Dooley, Mr. Patrick    male  32.0

In [236]:
df.iloc[9:25, 2:5]

Pclass                                               Name     Sex
10       3                    Sandstrom, Miss. Marguerite Rut  female
11       1                           Bonnell, Miss. Elizabeth  female
12       3                     Saundercock, Mr. William Henry    male
13       3                        Andersson, Mr. Anders Johan    male
14       3               Vestrom, Miss. Hulda Amanda Adolfina  female
15       2                   Hewlett, Mrs. (Mary D Kingcome)   female
16       3                               Rice, Master. Eugene    male
18       3  Vander Planke, Mrs. Julius (Emelia Maria Vande...  female
20       2                               Fynney, Mr. Joseph J    male
21       2                              Beesley, Mr. Lawrence    male
22       3                        McGowan, Miss. Anna "Annie"  female
23       1                       Sloper, Mr. William Thompson    male
24       3                      Palsson, Miss. Torborg Danira  female
25       3  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  female
27       1                     Fortune, Mr. Charles Alexander    male
30       1                           Uruchurtu, Don. Manuel E    male

In [ ]:
**Assign the name anonymous to the first 3 elements of the third column**

In [246]:
df

PassengerId   Survived     Pclass  \
0     anormnous  anormnous  anormnous   
1     anormnous  anormnous  anormnous   
2     anormnous  anormnous  anormnous   
3             4          1          1   
4             5          0          3   
..          ...        ...        ...   
885         886          0          3   
886         887          0          2   
887         888          1          1   
889         890          1          1   
890         891          0          3   

                                             Name        Sex        Age  \
0                                       anormnous  anormnous  anormnous   
1                                       anormnous  anormnous  anormnous   
2                                       anormnous  anormnous  anormnous   
3    Futrelle, Mrs. Jacques Heath (Lily May Peel)     female         35   
4                        Allen, Mr. William Henry       male         35   
..                                            ...        ...        ...   
885          Rice, Mrs. William (Margaret Norton)     female         39   
886                         Montvila, Rev. Juozas       male         27   
887                  Graham, Miss. Margaret Edith     female         19   
889                         Behr, Mr. Karl Howell       male         26   
890                           Dooley, Mr. Patrick       male         32   

         SibSp      Parch     Ticket       Fare      Cabin   Embarked  
0    anormnous  anormnous  anormnous  anormnous  anormnous  anormnous  
1    anormnous  anormnous  anormnous  anormnous  anormnous  anormnous  
2    anormnous  anormnous  anormnous  anormnous  anormnous  anormnous  
3            1          0     113803       53.1       C123          S  
4            0          0     373450       8.05        NaN          S  
..         ...        ...        ...        ...        ...        ...  
885          0          5     382652     29.125        NaN          Q  
886          0          0     211536         13        NaN          S  
887          0          0     112053         30        B42          S  
889          0          0     111369         30       C148          C  
890          0          0     370376       7.75        NaN          Q  

[714 rows x 12 columns]

In [247]:
k=df['Name']

In [248]:
k[0:3]='dd'

In [249]:
k

0                                                dd
1                                                dd
2                                                dd
3      Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                          Allen, Mr. William Henry
                           ...                     
885            Rice, Mrs. William (Margaret Norton)
886                           Montvila, Rev. Juozas
887                    Graham, Miss. Margaret Edith
889                           Behr, Mr. Karl Howell
890                             Dooley, Mr. Patrick
Name: Name, Length: 714, dtype: object

In [243]:
df.iloc[3, 0:3]

PassengerId    4
Survived       1
Pclass         1
Name: 3, dtype: object

In [ ]:
**My colleague requested the Titanic data as a spreadsheet.**

**Number of unique passanger**

In [9]:
df['PassengerId'].unique()

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [10]:
df['PassengerId'].count()

891

In [ ]:
Total number of passangers are 891.

**Number of unique passanger that survived**

In [21]:
df[df['Survived'] ==1]

PassengerId  Survived  Pclass  \
1              2         1       1   
2              3         1       3   
3              4         1       1   
8              9         1       3   
9             10         1       2   
..           ...       ...     ...   
875          876         1       3   
879          880         1       1   
880          881         1       2   
887          888         1       1   
889          890         1       1   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
..                                                 ...     ...   ...    ...   
875                   Najib, Miss. Adele Kiamie "Jane"  female  15.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
880       Shelley, Mrs. William (Imanita Parrish Hall)  female  25.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
889                              Behr, Mr. Karl Howell    male  26.0      0   

     Parch            Ticket     Fare Cabin Embarked  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
8        2            347742  11.1333   NaN        S  
9        0            237736  30.0708   NaN        C  
..     ...               ...      ...   ...      ...  
875      0              2667   7.2250   NaN        C  
879      1             11767  83.1583   C50        C  
880      1            230433  26.0000   NaN        S  
887      0            112053  30.0000   B42        S  
889      0            111369  30.0000  C148        C  

[342 rows x 12 columns]

In [22]:
df[df['Survived'] ==1].count()

PassengerId    342
Survived       342
Pclass         342
Name           342
Sex            342
Age            290
SibSp          342
Parch          342
Ticket         342
Fare           342
Cabin          136
Embarked       340
dtype: int64

In [ ]:
342 passangers survived

In [ ]:
**Number of passanger that survived were females** 

In [23]:
number_of_passangers_that_survived =df[df['Survived'] ==1]

In [24]:
number_of_passangers_that_survived

PassengerId  Survived  Pclass  \
1              2         1       1   
2              3         1       3   
3              4         1       1   
8              9         1       3   
9             10         1       2   
..           ...       ...     ...   
875          876         1       3   
879          880         1       1   
880          881         1       2   
887          888         1       1   
889          890         1       1   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
..                                                 ...     ...   ...    ...   
875                   Najib, Miss. Adele Kiamie "Jane"  female  15.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
880       Shelley, Mrs. William (Imanita Parrish Hall)  female  25.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
889                              Behr, Mr. Karl Howell    male  26.0      0   

     Parch            Ticket     Fare Cabin Embarked  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
8        2            347742  11.1333   NaN        S  
9        0            237736  30.0708   NaN        C  
..     ...               ...      ...   ...      ...  
875      0              2667   7.2250   NaN        C  
879      1             11767  83.1583   C50        C  
880      1            230433  26.0000   NaN        S  
887      0            112053  30.0000   B42        S  
889      0            111369  30.0000  C148        C  

[342 rows x 12 columns]

In [29]:
df[(df['Survived'] ==1) & (df['Sex'] =='female')]

PassengerId  Survived  Pclass  \
1              2         1       1   
2              3         1       3   
3              4         1       1   
8              9         1       3   
9             10         1       2   
..           ...       ...     ...   
874          875         1       2   
875          876         1       3   
879          880         1       1   
880          881         1       2   
887          888         1       1   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
..                                                 ...     ...   ...    ...   
874              Abelson, Mrs. Samuel (Hannah Wizosky)  female  28.0      1   
875                   Najib, Miss. Adele Kiamie "Jane"  female  15.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
880       Shelley, Mrs. William (Imanita Parrish Hall)  female  25.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   

     Parch            Ticket     Fare Cabin Embarked  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
8        2            347742  11.1333   NaN        S  
9        0            237736  30.0708   NaN        C  
..     ...               ...      ...   ...      ...  
874      0         P/PP 3381  24.0000   NaN        C  
875      0              2667   7.2250   NaN        C  
879      1             11767  83.1583   C50        C  
880      1            230433  26.0000   NaN        S  
887      0            112053  30.0000   B42        S  

[233 rows x 12 columns]

In [ ]:
342 of the survived passangers are females

In [ ]:
**What is the highest fare paid ?**

In [30]:
df['Fare'].max()

512.3292

In [ ]:
What is the lowest fare paid ?

In [31]:
df['Fare'].min()

0.0

In [ ]:
What is the lowest fare paid that is not equal to 0?

In [33]:
df[df['Fare'] != 0].min()

PassengerId                      1
Survived                         0
Pclass                           1
Name           Abbing, Mr. Anthony
Sex                         female
Age                           0.42
SibSp                            0
Parch                            0
Ticket                      110152
Fare                        4.0125
dtype: object

In [50]:
df.Fare.nsmallest(16).iloc[-1]

4.0125

In [ ]:
4.0125 is the lowest fair paid

In [ ]:
What is the median fare paid ?

In [51]:
df['Fare'].mean()

32.2042079685746

In [ ]:
How many people paid more than the median fare developed above?

In [52]:
median_above = df['Fare']>32.2042079685746

0      False
1       True
2      False
3       True
4      False
       ...  
886    False
887    False
888    False
889    False
890    False
Name: Fare, Length: 891, dtype: bool

In [55]:
df[df['Fare']>32.2042079685746].count()

PassengerId    211
Survived       211
Pclass         211
Name           211
Sex            211
Age            183
SibSp          211
Parch          211
Ticket         211
Fare           211
Cabin          139
Embarked       209
dtype: int64

In [88]:
df['Fare']>df['Fare'].mean()

0      False
1       True
2      False
3       True
4      False
       ...  
886    False
887    False
888    False
889    False
890    False
Name: Fare, Length: 891, dtype: bool

In [90]:
df[df['Fare']>df['Fare'].mean()].count()

PassengerId    211
Survived       211
Pclass         211
Name           211
Sex            211
Age            183
SibSp          211
Parch          211
Ticket         211
Fare           211
Cabin          139
Embarked       209
dtype: int64

In [ ]:
211 people paid more than mean amount


In [ ]:
How many people had booked Cabin is c?

In [93]:
(df['Cabin'][0]=='C').count()

AttributeError: 'bool' object has no attribute 'count'

In [68]:
df.apply(lambda x: True if x['Fare'] > 32.2042079685746 else False , axis=1)


0      False
1       True
2      False
3       True
4      False
       ...  
886    False
887    False
888    False
889    False
890    False
Length: 891, dtype: bool

In [87]:
k = df.apply(lambda x: True if x['Fare'] > 32.2042079685746 else False , axis=1)
if k ==True:
    k.count()
else:
     print(none)

    


ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [67]:
df.groupby(df['Fare']).apply(lambda x: len(x[x>3]))

TypeError: '>' not supported between instances of 'str' and 'int'

In [61]:
df.groupby('Fare').apply(lambda x: len(x[x>3]))

TypeError: '>' not supported between instances of 'str' and 'int'

In [59]:
(median_above ==True).count()

AttributeError: 'bool' object has no attribute 'count'

In [56]:
df[df['Fare']>32.2042079685746].unique()

AttributeError: 'DataFrame' object has no attribute 'unique'

In [11]:
df['Survived'].unique()

array([0, 1])

In [41]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
885          886         0       3   
886          887         0       2   
887          888         1       1   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked     Names  
0        0         A/5 21171   7.2500   NaN        S  Anormous  
1        0          PC 17599  71.2833   C85        C  Anormous  
2        0  STON/O2. 3101282   7.9250   NaN        S  Anormous  
3        0            113803  53.1000  C123        S  Anormous  
4        0            373450   8.0500   NaN        S  Anormous  
..     ...               ...      ...   ...      ...       ...  
885      5            382652  29.1250   NaN        Q  Anormous  
886      0            211536  13.0000   NaN        S  Anormous  
887      0            112053  30.0000   B42        S  Anormous  
889      0            111369  30.0000  C148        C  Anormous  
890      0            370376   7.7500   NaN        Q  Anormous  

[714 rows x 13 columns]

In [43]:
df.groupby('Sex')['Age'].mean()


Sex
female    27.915709
male      30.726645
Name: Age, dtype: float64

In [50]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
885          886         0       3   
886          887         0       2   
887          888         1       1   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked     Names  
0        0         A/5 21171   7.2500   NaN        S  Anormous  
1        0          PC 17599  71.2833   C85        C  Anormous  
2        0  STON/O2. 3101282   7.9250   NaN        S  Anormous  
3        0            113803  53.1000  C123        S  Anormous  
4        0            373450   8.0500   NaN        S  Anormous  
..     ...               ...      ...   ...      ...       ...  
885      5            382652  29.1250   NaN        Q  Anormous  
886      0            211536  13.0000   NaN        S  Anormous  
887      0            112053  30.0000   B42        S  Anormous  
889      0            111369  30.0000  C148        C  Anormous  
890      0            370376   7.7500   NaN        Q  Anormous  

[714 rows x 13 columns]

In [ ]:
What is the mean ticket fare price for each of the sex and cabin class combinations?

In [60]:
df.groupby('Sex')['Fare'].mean()


Sex
female    47.582759
male      27.268836
Name: Fare, dtype: float64

In [64]:
df.groupby(['Sex','Pclass'])['Fare'].mean()

Sex     Pclass
female  1         107.946275
        2          21.951070
        3          15.875369
male    1          71.142781
        2          21.113131
        3          12.162695
Name: Fare, dtype: float64

In [ ]:
What is the number of passengers in each of the cabin classes?

In [69]:
df['Pclass'].value_counts()

3    355
1    186
2    173
Name: Pclass, dtype: int64

In [71]:
df.groupby('Pclass').count()

PassengerId  Survived  Name  Sex  Age  SibSp  Parch  Ticket  Fare  \
Pclass                                                                      
1               186       186   186  186  186    186    186     186   186   
2               173       173   173  173  173    173    173     173   173   
3               355       355   355  355  355    355    355     355   355   

        Cabin  Embarked  Names  
Pclass                          
1         160       184    186  
2          15       173    173  
3          10       355    355

In [ ]:
Make all name characters lowercase

In [74]:
df["Name"].str.lower()

0                                braund, mr. owen harris
1      cumings, mrs. john bradley (florence briggs th...
2                                 heikkinen, miss. laina
3           futrelle, mrs. jacques heath (lily may peel)
4                               allen, mr. william henry
                             ...                        
885                 rice, mrs. william (margaret norton)
886                                montvila, rev. juozas
887                         graham, miss. margaret edith
889                                behr, mr. karl howell
890                                  dooley, mr. patrick
Name: Name, Length: 714, dtype: object

In [ ]:
Create a new column Surname that contains the surname of the Passengers by extracting the part before the comma.

In [78]:
df.insert(1, 'New Column2', (df['Name'].split('.')))


AttributeError: 'Series' object has no attribute 'split'

In [ ]:
df.columns.get_loc("pear")

In [19]:
(df['Survived']==1).count()

891

In [ ]:
df_sort3['Car name']

In [ ]:
df_sort3['Car name'].unique() # unique 

In [ ]:
len(df_sort3['Car name'].unique().tolist()) # to do list

The **info()** function gives some information about the data type: string float or null (missing values).

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column                           Non-Null Count  Dtype  
---  ------                           --------------  -----  
 0   X Coordinate                     1000 non-null   float64
 1   Y Coordinate                     1000 non-null   int64  
 2   Measured Depth (m)               1000 non-null   float64
 3   Deviation (True/False)           1000 non-null   bool   
 4   Surface-Casing Weight (kg/m)     593 non-null    float64
 5   Production-Casing Size (mm)      913 non-null    float64
 6   Production-Casing Weight (kg/m)  547 non-null    float64
 7   Bore. Temp. (degC)               801 non-null    float64
 8   Prod. Formation                  1000 non-null   object 
 9   Porosity (fraction)              1000 non-null   float64
 10  Permeability (Darcy)             1000 non-null   float64
 11  OIL Prod. (e3m3/month)           1000 non-null   float64
dtypes: bool(1), float64(9

The **describe** function gives some statistical analysis for each column if the data type is not string.

In [4]:
df.describe()

X Coordinate  Y Coordinate  Measured Depth (m)  \
count   1000.000000   1000.000000         1000.000000   
mean     432.893400    489.749000         1364.379300   
std      172.206682    243.547912          855.633567   
min       12.300000     36.000000          276.000000   
25%      325.425000    339.750000          704.000000   
50%      487.250000    480.000000         1066.000000   
75%      581.675000    596.000000         1790.000000   
max      648.800000   1172.000000         6363.000000   

       Surface-Casing Weight (kg/m)  Production-Casing Size (mm)  \
count                    593.000000                   913.000000   
mean                      42.906745                   142.495290   
std                       25.877438                    25.953205   
min                       14.100000                    13.700000   
25%                       35.700000                   114.300000   
50%                       35.700000                   139.700000   
75%                       48.100000                   177.800000   
max                      595.000000                   219.100000   

       Production-Casing Weight (kg/m)  Bore. Temp. (degC)  \
count                       547.000000          801.000000   
mean                         23.260512           40.774032   
std                           7.137579           21.256825   
min                          10.800000            5.000000   
25%                          17.300000           27.000000   
50%                          20.800000           33.000000   
75%                          25.300000           53.000000   
max                          53.600000          255.000000   

       Porosity (fraction)  Permeability (Darcy)  OIL Prod. (e3m3/month)  
count          1000.000000           1000.000000             1000.000000  
mean              0.141840              5.269140               60.003280  
std               0.074501              8.665687              234.814659  
min               0.000000              0.050000                0.000000  
25%               0.089750              1.040000                0.000000  
50%               0.141000              2.480000                4.715000  
75%               0.192000              5.752500               33.117500  
max               0.400000             94.510000             3425.530000

# Data Cleaning

## Missing (NaN) Values 

It is ideal to have valid value for every rows and columns. In reality, missing values is one of the main challenges faced by machine learning. There are some approaches in practice to deal with missing values. Majority of ML cant handle the NAN vales automatically.

**Option 1: Drop Column**

One naive approach is to remove columns that have missing values with **drop()** function.

In [5]:
df

X Coordinate  Y Coordinate  Measured Depth (m)  Deviation (True/False)  \
0           352.6           372              2145.8                   False   
1           435.7           551              1638.0                    True   
2            37.7           788              3984.0                    True   
3           346.7           311              3809.0                    True   
4           254.6           727              2335.0                    True   
..            ...           ...                 ...                     ...   
995          92.5           767              1466.0                   False   
996         548.3           475               749.8                   False   
997         593.4           456               683.7                   False   
998         540.9           328              1346.0                    True   
999         617.8           377               844.0                   False   

     Surface-Casing Weight (kg/m)  Production-Casing Size (mm)  \
0                             NaN                        114.3   
1                            25.3                        114.3   
2                            35.7                        114.3   
3                            41.7                        114.3   
4                            53.6                          NaN   
..                            ...                          ...   
995                          35.7                        139.7   
996                           NaN                        114.3   
997                           NaN                        177.8   
998                          25.3                        114.3   
999                          35.7                        139.7   

     Production-Casing Weight (kg/m)  Bore. Temp. (degC) Prod. Formation  \
0                                NaN                53.0      Shale-Sand   
1                               17.3                 NaN            Sand   
2                               22.5                 NaN           Shale   
3                               17.3                 NaN            Sand   
4                                NaN                32.0            Sand   
..                               ...                 ...             ...   
995                             20.8                51.0            Sand   
996                              NaN                28.0           Shale   
997                              NaN                26.0      Shale-Sand   
998                             14.1                 NaN           Shale   
999                             20.8                27.0      Shale-Sand   

     Porosity (fraction)  Permeability (Darcy)  OIL Prod. (e3m3/month)  
0                  0.224                 12.25                  108.75  
1                  0.118                  4.11                    0.33  
2                  0.121                  1.99                   21.87  
3                  0.170                  5.84                   46.30  
4                  0.158                  5.25                   17.53  
..                   ...                   ...                     ...  
995                0.230                  6.26                    8.74  
996                0.017                  0.48                    0.00  
997                0.332                 49.75                  832.45  
998                0.111                  0.59                    0.00  
999                0.292                  9.95                  153.43  

[1000 rows x 12 columns]

In [6]:
Select_column=column[3:8] # Select columns that have missing #columns described above # look at the non-null columns above
Select_column

['Deviation (True/False)',
 'Surface-Casing Weight (kg/m)',
 'Production-Casing Size (mm)',
 'Production-Casing Weight (kg/m)',
 'Bore. Temp. (degC)']

In [7]:
df_drop_c=df.copy() # Copy to avoid modifying the original data
df_drop_c.drop(Select_column,axis=1, inplace=True)  # Drop selected 5 columns # axis =1 column #inplace means if this condition is applicable follow through
# drop function has default axis = 0 it will drop a row
df_drop_c




X Coordinate  Y Coordinate  Measured Depth (m) Prod. Formation  \
0           352.6           372              2145.8      Shale-Sand   
1           435.7           551              1638.0            Sand   
2            37.7           788              3984.0           Shale   
3           346.7           311              3809.0            Sand   
4           254.6           727              2335.0            Sand   
..            ...           ...                 ...             ...   
995          92.5           767              1466.0            Sand   
996         548.3           475               749.8           Shale   
997         593.4           456               683.7      Shale-Sand   
998         540.9           328              1346.0           Shale   
999         617.8           377               844.0      Shale-Sand   

     Porosity (fraction)  Permeability (Darcy)  OIL Prod. (e3m3/month)  
0                  0.224                 12.25                  108.75  
1                  0.118                  4.11                    0.33  
2                  0.121                  1.99                   21.87  
3                  0.170                  5.84                   46.30  
4                  0.158                  5.25                   17.53  
..                   ...                   ...                     ...  
995                0.230                  6.26                    8.74  
996                0.017                  0.48                    0.00  
997                0.332                 49.75                  832.45  
998                0.111                  0.59                    0.00  
999                0.292                  9.95                  153.43  

[1000 rows x 7 columns]

In [7]:
df_drop_c.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   X Coordinate            1000 non-null   float64
 1   Y Coordinate            1000 non-null   int64  
 2   Measured Depth (m)      1000 non-null   float64
 3   Prod. Formation         1000 non-null   object 
 4   Porosity (fraction)     1000 non-null   float64
 5   Permeability (Darcy)    1000 non-null   float64
 6   OIL Prod. (e3m3/month)  1000 non-null   float64
dtypes: float64(5), int64(1), object(1)
memory usage: 54.8+ KB


This approach is not reliable since the information of 5 columns without missing values have been removed from data set.

**Option 2: Drop Row**

Another approach is to remove rows that have missing values with **dropna()** function.

In [8]:
df_drop_=df.copy() # Copy to avoid modifying the original data
df_drop_r=df_drop_.dropna() # Drop rows with missing values
df_drop_r

X Coordinate  Y Coordinate  Measured Depth (m)  Deviation (True/False)  \
6           636.9           462               713.0                    True   
7           556.2           441               761.0                   False   
8           572.0           521               587.0                   False   
10          366.2           385              1801.0                   False   
14          648.7           275               920.0                   False   
..            ...           ...                 ...                     ...   
989          44.1           787              1895.0                   False   
990         487.2            81              1033.0                    True   
991         607.4           526               668.0                    True   
995          92.5           767              1466.0                   False   
999         617.8           377               844.0                   False   

     Surface-Casing Weight (kg/m)  Production-Casing Size (mm)  \
6                            48.1                        177.8   
7                            35.7                        139.7   
8                            25.3                        114.3   
10                           35.7                        139.7   
14                           35.7                        139.7   
..                            ...                          ...   
989                          35.7                        139.7   
990                          35.7                        139.7   
991                          48.1                        177.8   
995                          35.7                        139.7   
999                          35.7                        139.7   

     Production-Casing Weight (kg/m)  Bore. Temp. (degC) Prod. Formation  \
6                               25.3                27.0           Shale   
7                               20.8                28.0            Sand   
8                               14.1                15.0           Shale   
10                              25.3                52.0      Shale-Sand   
14                              20.8                30.0           Shale   
..                               ...                 ...             ...   
989                             23.1                66.0           Shale   
990                             20.8                30.0           Shale   
991                             25.3                14.0      Shale-Sand   
995                             20.8                51.0            Sand   
999                             20.8                27.0      Shale-Sand   

     Porosity (fraction)  Permeability (Darcy)  OIL Prod. (e3m3/month)  
6                  0.128                  0.70                    0.00  
7                  0.055                  0.36                    0.00  
8                  0.033                  0.46                    0.00  
10                 0.147                  3.15                    5.80  
14                 0.104                  0.38                    0.00  
..                   ...                   ...                     ...  
989                0.144                 11.73                   22.01  
990                0.144                  0.99                    0.00  
991                0.000                  0.45                    0.00  
995                0.230                  6.26                    8.74  
999                0.292                  9.95                  153.43  

[426 rows x 12 columns]

In [9]:
df_drop_r.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 426 entries, 6 to 999
Data columns (total 12 columns):
 #   Column                           Non-Null Count  Dtype  
---  ------                           --------------  -----  
 0   X Coordinate                     426 non-null    float64
 1   Y Coordinate                     426 non-null    int64  
 2   Measured Depth (m)               426 non-null    float64
 3   Deviation (True/False)           426 non-null    bool   
 4   Surface-Casing Weight (kg/m)     426 non-null    float64
 5   Production-Casing Size (mm)      426 non-null    float64
 6   Production-Casing Weight (kg/m)  426 non-null    float64
 7   Bore. Temp. (degC)               426 non-null    float64
 8   Prod. Formation                  426 non-null    object 
 9   Porosity (fraction)              426 non-null    float64
 10  Permeability (Darcy)             426 non-null    float64
 11  OIL Prod. (e3m3/month)           426 non-null    float64
dtypes: bool(1), float64(9)

This approach is also not recommend because number of data (rows) have decreased from 1000 to 426.

**Option 3: Replace with Median (mean)**

A common practice is to replace missing values with the median (mean) value for that column. The median is the middle value of a list that 50% are less and 50% are bigger. See [Median](https://www.mathsisfun.com/median.html). The following code replaces all missing values in 5 columns with the median value of each column values.

In [58]:
df_im=df.copy() # name of new data set

# Get the median of each variable and replace the missing values with median
for i in range(len(Select_column)): #problem data set 
    P50 = df[Select_column[i]].median() # Calculate median of each column [] and then median()
    df_im[Select_column[i]] = df_im[Select_column[i]].fillna(P50)   # replace NaN with median(P50)
    # print(P50) # find P50 in each column and see if it has been replaced
df_im

X Coordinate  Y Coordinate  Measured Depth (m)  Deviation (True/False)  \
0           352.6           372              2145.8                   False   
1           435.7           551              1638.0                    True   
2            37.7           788              3984.0                    True   
3           346.7           311              3809.0                    True   
4           254.6           727              2335.0                    True   
..            ...           ...                 ...                     ...   
995          92.5           767              1466.0                   False   
996         548.3           475               749.8                   False   
997         593.4           456               683.7                   False   
998         540.9           328              1346.0                    True   
999         617.8           377               844.0                   False   

     Surface-Casing Weight (kg/m)  Production-Casing Size (mm)  \
0                            35.7                        114.3   
1                            25.3                        114.3   
2                            35.7                        114.3   
3                            41.7                        114.3   
4                            53.6                        139.7   
..                            ...                          ...   
995                          35.7                        139.7   
996                          35.7                        114.3   
997                          35.7                        177.8   
998                          25.3                        114.3   
999                          35.7                        139.7   

     Production-Casing Weight (kg/m)  Bore. Temp. (degC) Prod. Formation  \
0                               20.8                53.0      Shale-Sand   
1                               17.3                33.0            Sand   
2                               22.5                33.0           Shale   
3                               17.3                33.0            Sand   
4                               20.8                32.0            Sand   
..                               ...                 ...             ...   
995                             20.8                51.0            Sand   
996                             20.8                28.0           Shale   
997                             20.8                26.0      Shale-Sand   
998                             14.1                33.0           Shale   
999                             20.8                27.0      Shale-Sand   

     Porosity (fraction)  Permeability (Darcy)  OIL Prod. (e3m3/month)  
0                  0.224                 12.25                  108.75  
1                  0.118                  4.11                    0.33  
2                  0.121                  1.99                   21.87  
3                  0.170                  5.84                   46.30  
4                  0.158                  5.25                   17.53  
..                   ...                   ...                     ...  
995                0.230                  6.26                    8.74  
996                0.017                  0.48                    0.00  
997                0.332                 49.75                  832.45  
998                0.111                  0.59                    0.00  
999                0.292                  9.95                  153.43  

[1000 rows x 12 columns]

In [11]:
df_im.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column                           Non-Null Count  Dtype  
---  ------                           --------------  -----  
 0   X Coordinate                     1000 non-null   float64
 1   Y Coordinate                     1000 non-null   int64  
 2   Measured Depth (m)               1000 non-null   float64
 3   Deviation (True/False)           1000 non-null   bool   
 4   Surface-Casing Weight (kg/m)     1000 non-null   float64
 5   Production-Casing Size (mm)      1000 non-null   float64
 6   Production-Casing Weight (kg/m)  1000 non-null   float64
 7   Bore. Temp. (degC)               1000 non-null   float64
 8   Prod. Formation                  1000 non-null   object 
 9   Porosity (fraction)              1000 non-null   float64
 10  Permeability (Darcy)             1000 non-null   float64
 11  OIL Prod. (e3m3/month)           1000 non-null   float64
dtypes: bool(1), float64(9

## Remove Outliers 

Outliers are usually extreme high or low values that are different from pattern of majority data. Outliers should be removed from dataset (we should be careful not to consider novelty as outlier). A straightforward approach to detect outliers are several (n) [standard deviations](https://www.mathsisfun.com/data/standard-deviation.html) from the mean $m\pm n\sigma$ ($m$=mean, $\sigma$=standard deviation). For example, an outlier can bigger than $m+ 3\sigma $ or less than can bigger than $m- 3\sigma $. The following function can be used to apply this approach.    

In [ ]:
outlier is x in normal rnage but not y..top in middle
high verage points have ..near y rught botyom

In [55]:
def outlier_remove(df, n,name):
    """Delete rows for a specified column where values are out of +/- n*sd standard deviations
    
    df  : Pandas dataframe
    n   : n in the equation 𝑚±𝑛𝜎
    name: Column name
    """
    mean=df[name].mean() # Calclute mean of column
    sd=df[name].std()  # Calclute standard deviation of column
    drop_r = df.index[(mean -n * sd> df[name]) | (mean+n * sd< df[name])] # Find data that are not within 𝑚±𝑛𝜎 #drop these outlier
    df.drop(drop_r, axis=0, inplace=True) # Drop data # inplace = True - drop these outliers wherever it is true #condition satuisfy outlier dropped
    df.reset_index(inplace=True, drop=True) # Reset index 

In [56]:
# Drop outliers in last column 'OIL Prod. (e3m3/month)'
df_im_out=df_im.copy()  # copy data again
outlier_remove(df_im_out,n=3,name='OIL Prod. (e3m3/month)')# outlier removal column # 3 IS STD DEVIATION
df_im_out

X Coordinate  Y Coordinate  Measured Depth (m)  Deviation (True/False)  \
0           352.6           372              2145.8                   False   
1           435.7           551              1638.0                    True   
2            37.7           788              3984.0                    True   
3           346.7           311              3809.0                    True   
4           254.6           727              2335.0                    True   
..            ...           ...                 ...                     ...   
994         535.5           788              1744.0                    True   
995          92.5           767              1466.0                   False   
996         548.3           475               749.8                   False   
998         540.9           328              1346.0                    True   
999         617.8           377               844.0                   False   

     Surface-Casing Weight (kg/m)  Production-Casing Size (mm)  \
0                            35.7                        114.3   
1                            25.3                        114.3   
2                            35.7                        114.3   
3                            41.7                        114.3   
4                            53.6                        139.7   
..                            ...                          ...   
994                          71.4                        139.7   
995                          35.7                        139.7   
996                          35.7                        114.3   
998                          25.3                        114.3   
999                          35.7                        139.7   

     Production-Casing Weight (kg/m)  Bore. Temp. (degC) Prod. Formation  \
0                               20.8                53.0      Shale-Sand   
1                               17.3                33.0            Sand   
2                               22.5                33.0           Shale   
3                               17.3                33.0            Sand   
4                               20.8                32.0            Sand   
..                               ...                 ...             ...   
994                             20.8                28.0            Sand   
995                             20.8                51.0            Sand   
996                             20.8                28.0           Shale   
998                             14.1                33.0           Shale   
999                             20.8                27.0      Shale-Sand   

     Porosity (fraction)  Permeability (Darcy)  OIL Prod. (e3m3/month)  
0                  0.224                 12.25                  108.75  
1                  0.118                  4.11                    0.33  
2                  0.121                  1.99                   21.87  
3                  0.170                  5.84                   46.30  
4                  0.158                  5.25                   17.53  
..                   ...                   ...                     ...  
994                0.185                  2.79                    1.22  
995                0.230                  6.26                    8.74  
996                0.017                  0.48                    0.00  
998                0.111                  0.59                    0.00  
999                0.292                  9.95                  153.43  

[981 rows x 12 columns]

In [ ]:
DID THE CODE RUN YES SINCE THE ROWS HAVE DECREASED

## Concatenation 

A new data frames can be built by concatenating rows and columns. A new dataframe is created by concatenating two columns together 'Measured Depth (m)' and 'OIL Prod. (e3m3/month)' using the **concat()** function.

In [26]:
col_1= df_im['Measured Depth (m)']
col_2 = df_im['OIL Prod. (e3m3/month)']
result = pd.concat([col_1, col_2], axis=1)
result

Measured Depth (m)  OIL Prod. (e3m3/month)
0                2145.8                  108.75
1                1638.0                    0.33
2                3984.0                   21.87
3                3809.0                   46.30
4                2335.0                   17.53
..                  ...                     ...
995              1466.0                    8.74
996               749.8                    0.00
997               683.7                  832.45
998              1346.0                    0.00
999               844.0                  153.43

[1000 rows x 2 columns]

Two rows can be concatenated together using **concat()** function. The code below concatenates the first 4 rows and the last 3 rows of the previous dataset after imputation.

In [22]:
row_1= df_im[0:4]  # Retrieve first 4 rows
row_2 = df_im[-4:-1]  # Retrieve last 3 rows
result = pd.concat([row_1, row_2], axis=0) # Concatenate rows #axis = 0 concontanante rows tgether
result

X Coordinate  Y Coordinate  Measured Depth (m)  Deviation (True/False)  \
0           352.6           372              2145.8                   False   
1           435.7           551              1638.0                    True   
2            37.7           788              3984.0                    True   
3           346.7           311              3809.0                    True   
996         548.3           475               749.8                   False   
997         593.4           456               683.7                   False   
998         540.9           328              1346.0                    True   

     Surface-Casing Weight (kg/m)  Production-Casing Size (mm)  \
0                       42.906745                        114.3   
1                       25.300000                        114.3   
2                       35.700000                        114.3   
3                       41.700000                        114.3   
996                     42.906745                        114.3   
997                     42.906745                        177.8   
998                     25.300000                        114.3   

     Production-Casing Weight (kg/m)  Bore. Temp. (degC) Prod. Formation  \
0                          23.260512           53.000000      Shale-Sand   
1                          17.300000           40.774032            Sand   
2                          22.500000           40.774032           Shale   
3                          17.300000           40.774032            Sand   
996                        23.260512           28.000000           Shale   
997                        23.260512           26.000000      Shale-Sand   
998                        14.100000           40.774032           Shale   

     Porosity (fraction)  Permeability (Darcy)  OIL Prod. (e3m3/month)  
0                  0.224                 12.25                  108.75  
1                  0.118                  4.11                    0.33  
2                  0.121                  1.99                   21.87  
3                  0.170                  5.84                   46.30  
996                0.017                  0.48                    0.00  
997                0.332                 49.75                  832.45  
998                0.111                  0.59                    0.00

## Saving a Dataframe as CSV

You can simply save a dataframe as CSV by the following code.  The following code performs a shuffle and then saves a new copy.

In [19]:
filename="myfile.csv"
df_im.to_csv(filename, index=False) # index = False not writing row numbers #FILE IN PYTHON

# Shuffling, Grouping and Sorting

**Shuffling Dataset**

An example of shuffling is playing the game of cards. All the cards are collected at the end of each round of play, shuffled to ensure that cards are distributed randomly and each player receives cards based on chance. In Machine Learning, the data set should be split into training and validation datasets. So, shuffling is very important to avoid any element of bias/patterns in the split datasets.

If consistent shuffling of the data set is required for several times of running the code, a random seed can be used. See code below.

shuffle to remove bias,makes prediction very good or very bad

In [60]:
import numpy as np

#np.random.seed(82) 
df_shfl = df_im.reindex(np.random.permutation(df.index)) #df.index- reindex ur data, srart from 0
df_shfl.reset_index(inplace=True, drop=True) # Reset index # IF CODE IS NOT RUN THEN FIRST COLUMN INDEX WILL NOT START FROM 0
df_shfl[0:5]

X Coordinate  Y Coordinate  Measured Depth (m)  Deviation (True/False)  \
122         331.3           403              2370.0                   False   
544         572.5           453               749.0                   False   
962         609.8           529               639.0                    True   
984         415.4           177              1870.0                   False   
336         591.2           540               545.0                    True   

     Surface-Casing Weight (kg/m)  Production-Casing Size (mm)  \
122                          53.6                        139.7   
544                          35.7                        139.7   
962                          35.7                        139.7   
984                          35.7                        139.7   
336                          48.1                        177.8   

     Production-Casing Weight (kg/m)  Bore. Temp. (degC) Prod. Formation  \
122                             25.3                75.0           Shale   
544                             20.8                25.0           Shale   
962                             20.8                27.0      Shale-Sand   
984                             23.1                27.0            Sand   
336                             29.8                19.0      Shale-Sand   

     Porosity (fraction)  Permeability (Darcy)  OIL Prod. (e3m3/month)  
122                0.231                  3.39                   10.64  
544                0.022                  1.12                    0.00  
962                0.167                  2.85                   36.88  
984                0.063                  3.49                   10.21  
336                0.110                  6.98                    0.00

**Grouping Data Set**

Grouping is applied to summarize data. The following codes performs grouping; generating the mean and sum of
each category for feature 'Prod. Formation' in target variable 'OIL Prod. (e3m3/month)'. 

In [64]:
gb_mean=df_im.groupby('Prod. Formation')['OIL Prod. (e3m3/month)'].mean() #WHY DO WE NEED TO MENTION TARGET VARIABLE
gb_mean

Prod. Formation
Sand          64.015467
Shale         59.502943
Shale-Sand    54.482824
Name: OIL Prod. (e3m3/month), dtype: float64

In [21]:
gb_sum=df_im.groupby('Prod. Formation')['OIL Prod. (e3m3/month)'].sum()
gb_sum

Prod. Formation
Sand          19204.64
Shale         31536.56
Shale-Sand     9262.08
Name: OIL Prod. (e3m3/month), dtype: float64

**Sorting Data Set**

In [66]:
df_sort = df_im.sort_values(by='Measured Depth (m)', ascending=True) # sorted by meadured depthor by ascending order
# sort by one column
df_sort.reset_index(inplace=True, drop=True) # Reset index (first column) from lowest to highest -first column
df_sort

X Coordinate  Y Coordinate  Measured Depth (m)  Deviation (True/False)  \
0           132.0          1104               276.0                   False   
1            72.9           784               295.5                   False   
2           591.3           791               297.0                   False   
3           621.7           593               321.0                    True   
4           631.2           583               343.2                   False   
..            ...           ...                 ...                     ...   
995         179.8           628              5066.0                    True   
996         110.2           677              5116.0                    True   
997          48.6           718              5226.0                    True   
998         188.4           619              5790.0                    True   
999         343.2           383              6363.0                    True   

     Surface-Casing Weight (kg/m)  Production-Casing Size (mm)  \
0                            25.3                        114.3   
1                            25.3                        114.3   
2                            25.3                        114.3   
3                            53.6                        177.8   
4                            56.5                        139.7   
..                            ...                          ...   
995                          53.6                        139.7   
996                          35.7                        139.7   
997                          59.5                        139.7   
998                          53.6                        114.3   
999                          60.3                        139.7   

     Production-Casing Weight (kg/m)  Bore. Temp. (degC) Prod. Formation  \
0                               14.1                25.0           Shale   
1                               14.1                22.0           Shale   
2                               14.1                26.0           Shale   
3                               34.2                33.0           Shale   
4                               20.8                33.0            Sand   
..                               ...                 ...             ...   
995                             20.8                33.0           Shale   
996                             25.3                33.0            Sand   
997                             20.8                33.0           Shale   
998                             22.5                33.0           Shale   
999                             38.7                33.0            Sand   

     Porosity (fraction)  Permeability (Darcy)  OIL Prod. (e3m3/month)  
0                  0.142                  1.16                    0.00  
1                  0.000                  0.66                    0.00  
2                  0.142                 13.37                   72.26  
3                  0.091                  1.72                    0.00  
4                  0.168                  3.19                   19.23  
..                   ...                   ...                     ...  
995                0.114                  3.23                    0.00  
996                0.000                  0.13                    0.00  
997                0.249                  8.97                   83.09  
998                0.194                  4.03                    0.39  
999                0.239                  3.19                   12.26  

[1000 rows x 12 columns]

In [26]:
df_sort['X Coordinate'].values # do anything add it to pandas and save it to excel file

array([132. ,  72.9, 591.3, 621.7, 631.2, 451.8, 549.4, 581.6, 596.4,
       612.7, 607.4, 607.5, 609.8, 609.8, 597.2, 587.5, 588.4, 588.3,
       617.9, 597.3, 451.2, 589.3, 571.8, 597.2, 621.3, 607.6, 625.2,
       598.5, 603.8, 633.4, 545.5, 582.8, 537.3, 612.5, 524.6, 518.8,
       525.7, 578.7, 613.6, 638.3, 597.2, 591.4, 621.3, 636.5, 581.2,
       539.3, 593.7, 523.7, 563.2, 601.2, 587.3, 582.4, 436.9, 622.1,
       573.6, 617.9, 609.8, 603.3, 564.1, 604.2, 640.1, 602. , 624.2,
       550. , 601.7, 614.7, 606.7, 616.2, 617.9, 609.5, 636.6, 632.7,
       465.5, 626.4, 535. , 621. , 104.1, 601.5, 622. , 628.2, 537.7,
       607.4, 634. , 524.6, 648.8, 591.2, 481.8, 614.6, 598.8, 620.6,
       600.1, 602.5, 608.4, 613.9, 497.1, 615.4, 522. , 610.9, 619.4,
       594.8, 238.6, 614.9, 591.5, 597.2, 588.5, 611. , 574.9, 598.6,
       434.9, 617.2, 586.1, 624. , 595.4, 572. , 443.6, 617.6, 587.8,
       616.2, 433.2, 593.9, 580.5, 609.4, 607. , 608.5, 496.1, 494.1,
       417. , 490.9,

# Feature Engineering

Feature engineering is the process of extracting new feature from raw data via data mining techniques. The new features can be used to enhance the performance of machine learning algorithms. New features could also be calculated from the other fields. For the data set WPD.csv, we can add the product of "Surface-Casing Weight (kg/m)" and "Production-Casing Weight (kg/m)" as a new data set.

In [ ]:
CHOOSE TEH MOST IMPORTNAT FEATURES FOR UR CALCULATION 
GENERATE A FEATURE /column based on the existing variables in data
REMOVE A FEATURE

In [35]:
df_im_c=df_im.copy()
df_im.insert(1, 'New Column2', (df_im['Surface-Casing Weight (kg/m)']*df_im['Production-Casing Weight (kg/m)']).astype(float))
# 1 IS INDEX # cant run the code twice
df_im

X Coordinate  New Column2  New Column1  Y Coordinate  New Column  \
0           352.6   998.032860          998           372         998   
1           435.7   437.690000          437           551         437   
2            37.7   803.250000          803           788         803   
3           346.7   721.410000          721           311         721   
4           254.6  1246.763437         1246           727        1246   
..            ...          ...          ...           ...         ...   
995          92.5   742.560000          742           767         742   
996         548.3   998.032860          998           475         998   
997         593.4   998.032860          998           456         998   
998         540.9   356.730000          356           328         356   
999         617.8   742.560000          742           377         742   

     Measured Depth (m)  Deviation (True/False)  Surface-Casing Weight (kg/m)  \
0                2145.8                   False                     42.906745   
1                1638.0                    True                     25.300000   
2                3984.0                    True                     35.700000   
3                3809.0                    True                     41.700000   
4                2335.0                    True                     53.600000   
..                  ...                     ...                           ...   
995              1466.0                   False                     35.700000   
996               749.8                   False                     42.906745   
997               683.7                   False                     42.906745   
998              1346.0                    True                     25.300000   
999               844.0                   False                     35.700000   

     Production-Casing Size (mm)  Production-Casing Weight (kg/m)  \
0                      114.30000                        23.260512   
1                      114.30000                        17.300000   
2                      114.30000                        22.500000   
3                      114.30000                        17.300000   
4                      142.49529                        23.260512   
..                           ...                              ...   
995                    139.70000                        20.800000   
996                    114.30000                        23.260512   
997                    177.80000                        23.260512   
998                    114.30000                        14.100000   
999                    139.70000                        20.800000   

     Bore. Temp. (degC) Prod. Formation  Porosity (fraction)  \
0             53.000000      Shale-Sand                0.224   
1             40.774032            Sand                0.118   
2             40.774032           Shale                0.121   
3             40.774032            Sand                0.170   
4             32.000000            Sand                0.158   
..                  ...             ...                  ...   
995           51.000000            Sand                0.230   
996           28.000000           Shale                0.017   
997           26.000000      Shale-Sand                0.332   
998           40.774032           Shale                0.111   
999           27.000000      Shale-Sand                0.292   

     Permeability (Darcy)  OIL Prod. (e3m3/month)  
0                   12.25                  108.75  
1                    4.11                    0.33  
2                    1.99                   21.87  
3                    5.84                   46.30  
4                    5.25                   17.53  
..                    ...                     ...  
995                  6.26                    8.74  
996                  0.48                    0.00  
997                 49.75                  832.45  
998                  0.59            

# Standardize (Normalize) Values

Most Machine Learning algorithms require to standardize the input to have a reliable comparison between two values of different variables. For example, if you have variable one with a range of 3 to 1000 and variable two with range 1 to 3; we cannot have a good comparison since the highest value of variable two (3) is the lowest value in variable two. This inconsistency in data values leads to low performance in Machine Learning algorithms. So, it is highly recommended to standardize (normalize) your data to have the same the mean($\mu$) and the standard deviation ($\sigma$) before feeding Machine Learning algorithms. One very common Machine learning standardization (normalization) is the Z-Score:

$\Large z = \frac{x - \mu}{\sigma} $ 

where $ \mu = \frac{1}{n} \sum_{i=1}^n x_i$, $\sigma = \sqrt{\frac{1}{n} \sum_{i=1}^n (x_i - \mu)^2}$, $n$ is number of data. This ensures that each variable have $\mu=0$ and $\sigma=1$

This standardization should be applied for all features **except the target (label)**. For WPD.csv data set, the target is "OIL Prod. (e3m3/month)" that should not be changed. 

The following Python code replaces the 'Measured Depth (m)' with a z-score. This can be done for all variables.

In [ ]:
Not need in case of linear regression
20 minutes

In [ ]:
normalized - bell shaped
shandardization does not chnage the shape of distribution
We have high values for prod and low values for porosity
the range of data should not be so different
make the range of data same
deduct mean from evey element and divide by variance
so u make averge = 0 and std =1
standaize only features or predictors 
Do not standardize true and false or the final value or target or categorical variables or oil prod
more than one target - multi classification
Here is mutli features but predicting one variable
if one more target, i apply for one target and two target ..two single regression..assuming no correlation b/w them
if coorelation # apply at the same time

In [22]:
from scipy.stats import zscore

mean=df_im['Measured Depth (m)'].mean()
variance=df_im['Measured Depth (m)'].var()
print("Before standardization: Mean= ",int(mean), ", variance= ",int(variance))

df_im['Measured Depth (m)'] = zscore(df_im['Measured Depth (m)']) # zscore

mean=df_im['Measured Depth (m)'].mean() #mean of zscoare
variance=df_im['Measured Depth (m)'].var()
print("After standardization: Mean= ",int(mean), ", variance= ",int(variance))

Before standardization: Mean=  1364 , variance=  732108
After standardization: Mean=  0 , variance=  1


In [ ]:
make a loop and apply for all variables

In [23]:
df_im[0:5]

X Coordinate  New Column  Y Coordinate  Measured Depth (m)  \
0         352.6         742           372            0.913723   
1         435.7         437           551            0.319947   
2          37.7         803           788            3.063147   
3         346.7         721           311            2.858518   
4         254.6        1114           727            1.134956   

   Deviation (True/False)  Surface-Casing Weight (kg/m)  \
0                   False                          35.7   
1                    True                          25.3   
2                    True                          35.7   
3                    True                          41.7   
4                    True                          53.6   

   Production-Casing Size (mm)  Production-Casing Weight (kg/m)  \
0                        114.3                             20.8   
1                        114.3                             17.3   
2                        114.3                             22.5   
3                        114.3                             17.3   
4                        139.7                             20.8   

   Bore. Temp. (degC) Prod. Formation  Porosity (fraction)  \
0                53.0      Shale-Sand                0.224   
1                33.0            Sand                0.118   
2                33.0           Shale                0.121   
3                33.0            Sand                0.170   
4                32.0            Sand                0.158   

   Permeability (Darcy)  OIL Prod. (e3m3/month)  
0                 12.25                  108.75  
1                  4.11                    0.33  
2                  1.99                   21.87  
3                  5.84                   46.30  
4                  5.25                   17.53

# Categorical Values - CONVERT TEXT TO NUMBER

The input data for Machine Learning should be completely numeric which means any text should be converted to number. In the data set **WPD.csv**, the columns 'Deviation (True/False)' and 'Prod. Formation' have categorical values. Use **value_counts()** function to find out what categories exist and how many data belong to each category.

In [68]:
df_c=df_im.copy()
df_c['Deviation (True/False)'].value_counts()

False    652
True     348
Name: Deviation (True/False), dtype: int64

In [69]:
df_c['Prod. Formation'].value_counts()

Shale         530
Sand          300
Shale-Sand    170
Name: Prod. Formation, dtype: int64

We can replace each test with numbers starting from 0

In [70]:
df_c['Deviation (True/False)']=df_c['Deviation (True/False)'].replace(False, 0) # Replace False with 0
df_c['Deviation (True/False)']=df_c['Deviation (True/False)'].replace(True, 1)  # Replace True with 1
df_c[0:5]

X Coordinate  Y Coordinate  Measured Depth (m)  Deviation (True/False)  \
0         352.6           372              2145.8                     0.0   
1         435.7           551              1638.0                     1.0   
2          37.7           788              3984.0                     1.0   
3         346.7           311              3809.0                     1.0   
4         254.6           727              2335.0                     1.0   

   Surface-Casing Weight (kg/m)  Production-Casing Size (mm)  \
0                          35.7                        114.3   
1                          25.3                        114.3   
2                          35.7                        114.3   
3                          41.7                        114.3   
4                          53.6                        139.7   

   Production-Casing Weight (kg/m)  Bore. Temp. (degC) Prod. Formation  \
0                             20.8                53.0      Shale-Sand   
1                             17.3                33.0            Sand   
2                             22.5                33.0           Shale   
3                             17.3                33.0            Sand   
4                             20.8                32.0            Sand   

   Porosity (fraction)  Permeability (Darcy)  OIL Prod. (e3m3/month)  
0                0.224                 12.25                  108.75  
1                0.118                  4.11                    0.33  
2                0.121                  1.99                   21.87  
3                0.170                  5.84                   46.30  
4                0.158                  5.25                   17.53

In [71]:
df_c['Prod. Formation']=df_c['Prod. Formation'].replace('Shale', 0)       # Replace Shale with 0
df_c['Prod. Formation']=df_c['Prod. Formation'].replace('Sand', 1)        # Replace Sand with 1
df_c['Prod. Formation']=df_c['Prod. Formation'].replace('Shale-Sand', 2)  # Replace Shale-Sand with 2
df_c[0:5]

X Coordinate  Y Coordinate  Measured Depth (m)  Deviation (True/False)  \
0         352.6           372              2145.8                     0.0   
1         435.7           551              1638.0                     1.0   
2          37.7           788              3984.0                     1.0   
3         346.7           311              3809.0                     1.0   
4         254.6           727              2335.0                     1.0   

   Surface-Casing Weight (kg/m)  Production-Casing Size (mm)  \
0                          35.7                        114.3   
1                          25.3                        114.3   
2                          35.7                        114.3   
3                          41.7                        114.3   
4                          53.6                        139.7   

   Production-Casing Weight (kg/m)  Bore. Temp. (degC)  Prod. Formation  \
0                             20.8                53.0                2   
1                             17.3                33.0                1   
2                             22.5                33.0                0   
3                             17.3                33.0                1   
4                             20.8                32.0                1   

   Porosity (fraction)  Permeability (Darcy)  OIL Prod. (e3m3/month)  
0                0.224                 12.25                  108.75  
1                0.118                  4.11                    0.33  
2                0.121                  1.99                   21.87  
3                0.170                  5.84                   46.30  
4                0.158                  5.25                   17.53

One challenge with this representation is that Machine Learning algorithms consider two nearby values are more similar than two distant values. This may be fine for some cases (order of categories “bad”, “average”, “good”), but this is not always true. A common solution is to have one binary attribute per category. This is called **one-hot encoding**, because we only  have one attribute equal to 1 (hot), while the others are 0 (cold). 

shales bad, shell good, sand and shale is b/w, so change order
no ordering negative impact on prediction


One hot in coding - all values arer 0 except where category exists

In [81]:
One_hot = pd.get_dummies(['a','b'],prefix='Deviation')
print(One_hot)

   Deviation_a  Deviation_b
0            1            0
1            0            1


These dummies should be merged back into the data frame.  

In [82]:
One_hot = pd.get_dummies(df_im['Deviation (True/False)'],prefix='Deviation') # 2 categories 2 columns
print(One_hot[0:10]) # Just show the first 10

   Deviation_False  Deviation_True
0                1               0
1                0               1
2                0               1
3                0               1
4                0               1
5                1               0
6                0               1
7                1               0
8                1               0
9                0               1


In [83]:

df_one_hot = pd.concat([df_im,One_hot],axis=1) #df_im is data and one_hot is defined above
df_one_hot[0:5]
# run above code again otherwise it will show for shale inctead of deviation

X Coordinate  Y Coordinate  Measured Depth (m)  Deviation (True/False)  \
0         352.6           372              2145.8                   False   
1         435.7           551              1638.0                    True   
2          37.7           788              3984.0                    True   
3         346.7           311              3809.0                    True   
4         254.6           727              2335.0                    True   

   Surface-Casing Weight (kg/m)  Production-Casing Size (mm)  \
0                          35.7                        114.3   
1                          25.3                        114.3   
2                          35.7                        114.3   
3                          41.7                        114.3   
4                          53.6                        139.7   

   Production-Casing Weight (kg/m)  Bore. Temp. (degC) Prod. Formation  \
0                             20.8                53.0      Shale-Sand   
1                             17.3                33.0            Sand   
2                             22.5                33.0           Shale   
3                             17.3                33.0            Sand   
4                             20.8                32.0            Sand   

   Porosity (fraction)  Permeability (Darcy)  OIL Prod. (e3m3/month)  \
0                0.224                 12.25                  108.75   
1                0.118                  4.11                    0.33   
2                0.121                  1.99                   21.87   
3                0.170                  5.84                   46.30   
4                0.158                  5.25                   17.53   

   Deviation_False  Deviation_True  
0                1               0  
1                0               1  
2                0               1  
3                0               1  
4                0               1

This should be done for 'Prod. Formation' column.

In [84]:
One_hot = pd.get_dummies(df_im['Prod. Formation'],prefix='Formation') #Prefix='Formation is the prefix for new tab to be created
df_one_hot = pd.concat([df_one_hot,One_hot],axis=1)
df_one_hot[0:5]

X Coordinate  Y Coordinate  Measured Depth (m)  Deviation (True/False)  \
0         352.6           372              2145.8                   False   
1         435.7           551              1638.0                    True   
2          37.7           788              3984.0                    True   
3         346.7           311              3809.0                    True   
4         254.6           727              2335.0                    True   

   Surface-Casing Weight (kg/m)  Production-Casing Size (mm)  \
0                          35.7                        114.3   
1                          25.3                        114.3   
2                          35.7                        114.3   
3                          41.7                        114.3   
4                          53.6                        139.7   

   Production-Casing Weight (kg/m)  Bore. Temp. (degC) Prod. Formation  \
0                             20.8                53.0      Shale-Sand   
1                             17.3                33.0            Sand   
2                             22.5                33.0           Shale   
3                             17.3                33.0            Sand   
4                             20.8                32.0            Sand   

   Porosity (fraction)  Permeability (Darcy)  OIL Prod. (e3m3/month)  \
0                0.224                 12.25                  108.75   
1                0.118                  4.11                    0.33   
2                0.121                  1.99                   21.87   
3                0.170                  5.84                   46.30   
4                0.158                  5.25                   17.53   

   Deviation_False  Deviation_True  Formation_Sand  Formation_Shale  \
0                1               0               0                0   
1                0               1               1                0   
2                0               1               0                1   
3                0               1               1                0   
4                0               1               1                0   

   Formation_Shale-Sand  
0                     1  
1                     0  
2                     0  
3                     0  
4                     0

Finally, the original columns 'Deviation (True/False)' and 'Prod. Formation' should be removed. 

In [85]:
df_one_hot.drop(['Deviation (True/False)','Prod. Formation'], axis=1, inplace=True) # drop the oroginal columns# axis=1 in column


In [80]:
df_one_hot 

X Coordinate  Y Coordinate  Measured Depth (m)  \
0           352.6           372              2145.8   
1           435.7           551              1638.0   
2            37.7           788              3984.0   
3           346.7           311              3809.0   
4           254.6           727              2335.0   
..            ...           ...                 ...   
995          92.5           767              1466.0   
996         548.3           475               749.8   
997         593.4           456               683.7   
998         540.9           328              1346.0   
999         617.8           377               844.0   

     Surface-Casing Weight (kg/m)  Production-Casing Size (mm)  \
0                            35.7                        114.3   
1                            25.3                        114.3   
2                            35.7                        114.3   
3                            41.7                        114.3   
4                            53.6                        139.7   
..                            ...                          ...   
995                          35.7                        139.7   
996                          35.7                        114.3   
997                          35.7                        177.8   
998                          25.3                        114.3   
999                          35.7                        139.7   

     Production-Casing Weight (kg/m)  Bore. Temp. (degC)  Porosity (fraction)  \
0                               20.8                53.0                0.224   
1                               17.3                33.0                0.118   
2                               22.5                33.0                0.121   
3                               17.3                33.0                0.170   
4                               20.8                32.0                0.158   
..                               ...                 ...                  ...   
995                             20.8                51.0                0.230   
996                             20.8                28.0                0.017   
997                             20.8                26.0                0.332   
998                             14.1                33.0                0.111   
999                             20.8                27.0                0.292   

     Permeability (Darcy)  OIL Prod. (e3m3/month)  Deviation_False  \
0                   12.25                  108.75                1   
1                    4.11                    0.33                0   
2                    1.99                   21.87                0   
3                    5.84                   46.30                0   
4                    5.25                   17.53                0   
..                    ...                     ...              ...   
995                  6.26                    8.74                1   
996                  0.48                    0.00                1   
997                 49.75                  832.45                1   
998                  0.59                    0.00                0   
999                  9.95                  153.43                1   

     Deviation_True  Formation_Sand  Formation_Shale  Formation_Shale-Sand  \
0                 0               0                0                     1   
1                 1               1                0                     0   
2                 1               0                1                     0   
3                 1               1                0                     0   
4                 1               1                0                     0   
..              ...             ...              ...                   ...   
995               0               1                0                     0   
996               0               0                1                     0   
997               0               0

# Split Data to Training and Validation 

Machine Learning models should be evaluated based on prediction for never-before-seen data set. The models usually have high performance for the data that are trained by. However, the main aim of training is to have high performance on completely new data set. So, data are split into training and validation set. The machine learning models learn from the training data, but based on the validation data are evaluated: the data should be divided into training and validation set according to some ratio. The common ratios are 80% training and 20% validation. 
The image below shows how a model is trained on 80% of the data and then validated against the remaining 20%. Based on feedback performance on evaluation set, Machine learning algorithms are modified. This process is repeated until the model's performance is satisfied. This repetition also could lead to **information leak**. The model could perform well on the validation set but not on a new data set. So, sometimes, a portion of data are hold-out for testing. We will talk about this on the next lectures

<p>&nbsp;</p>
<img src="https://raw.githubusercontent.com/MehdiRezvandehy/Machine-Learning-Course-University-of-Calgary/master/Images/Fig4-1.png" alt="drawing" width="900"/>
<p>&nbsp;</p>

The following code splits the data into 80% training and 20% validation set.


In [ ]:
MODEL OVERFIT THE DATA AND BAD PERFORMANCE ONTESTING DATA

In [ ]:
GOOD PREDICTION/VALIDATION WITH TEST DATA WITH CROSS VALIDATION, CROSS VALIDATION TRAIN ON ONE FOLD AND PREDICT ON ANOTHER FOLD

In [33]:
import numpy as np

df = df.reindex(np.random.permutation(df.index)) #  Shuffle the data # GENERATE RANDOM #Exact code as before
df.reset_index(inplace=True, drop=True) # Reset index #Exact code as before
MASK = np.random.rand(len(df)) < 0.8    # 80%OF TEH VALUES LESS THAN 0.8 THAT R RANDOMLY GENERATED
df_train = pd.DataFrame(df[MASK])
df_validation = pd.DataFrame(df[~MASK])

print("Number of Training: "+ str(len(df_train)))
print("Number of Validation: "+  str(len(df_validation)))

Number of Training: 800
Number of Validation: 200


In [ ]:
Skilearn will provide a split

In [ ]:
IMPUTE FIRST TWO MISSING VALUES WITH MEDIAN
LAST ONE WITH MEAN

6 CONVERT TEXT TO NUMBER
#NOT ONE HOT CODING
#CATEGORYIES TO NUMBER


7 DIFFERNET DAYS